language: php

php:
    - 7.1
    - 7.2
    - 7.3

cache:
    directories:
    - "$HOME/.composer/cache"

before_install:
- if [[ $COVERAGE == false ]]; then phpenv config-rm xdebug.ini || true; fi
- |
    tfold () {
          title=$1
          fold=$(echo $title | sed -r 's/[^-_A-Za-z\d]+/./g')
          shift
          echo -e "travis_fold:start:$fold\\n\\e[1;34m$title\\e[0m"
          bash -xc "$*" 2>&1 &&
              echo "########################################" &&
              echo "########################################" &&
              echo -e "\\e[32mOK\\e[0m $title\\n\\ntravis_fold:end:$fold" ||
              ( echo -e "\\e[41mKO\\e[0m $title\\n" && exit 1 )
      }
      export -f tfold

install:
- composer update --no-progress --no-suggest --ansi --prefer-dist


stages:
- name: test
  if: branch = master AND tag IS blank
- name: release
  if: branch = master AND tag IS blank

script: tfold tty-group ./vendor/bin/phpunit --coverage-clover=coverage.xml && if [[ "$(php -v)" = 7.1.* ]]; then pip install --user codecov && codecov; fi

jobs:
    include:
    -   stage: release
        php: 7.1
        script: |
            npm i -g semantic-release@15@semantic-release/changelog @semantic-release/git @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator
            npx semantic-release